API_KEY='sk-proj-Ydso7o12f5NcxbeONGkKT3BlbkFJfhHqxJ1HrSHVwdTbSHEQ'
OPENAI_API_KEY="sk-proj-Ydso7o12f5NcxbeONGkKT3BlbkFJfhHqxJ1HrSHVwdTbSHEQ"
AMADEUS_API_KEY='5mi9L4GOWV8sG4pzZ6t7akPRXFmN6dAe'
AMADEUS_API_SECRET='Sw8hPUEyc8SXiOd6'
Pexels_API_KEY = "SybpjcP1VvLoFRpmV3OYdsdAHhonNIrr0DADxqpZveOUE6dhglVLrTei"
RAPID_API_KEY='199f789e81msh822e41127d3d294p182bd1jsn59d966b70175'
PEXELS_API_KEY='aX1oVcA9l4t1zj7k221MvHWgxVYZME44eCKo3szkQj3cqGqMIbyRpgdL'
X-RapidAPI-Key = "199f789e81msh822e41127d3d294p182bd1jsn59d966b70175"
X-RapidAPI-Host ="booking-com.p.rapidapi.com"

